DROP TABLE MEMBERS cascade constraints;
DROP TABLE CLUBS cascade constraints;
DROP TABLE STAFFS cascade constraints;
DROP TABLE USERS cascade constraints;
DROP TABLE CLUB_STAFF_MANAGEMENT cascade constraints;
DROP TABLE USER_APPLICATION cascade constraints;

DROP SEQUENCE user_id_seq;
DROP SEQUENCE club_id_seq;
DROP SEQUENCE staff_id_seq;
DROP SEQUENCE member_id_seq;
DROP SEQUENCE application_id_seq;


CREATE TABLE USERS (
    USERID          NUMBER(7),
    DISPLAYNAME     VARCHAR(255),
    EMAIL           VARCHAR2(255),
    USERPASSWORD        VARCHAR2(255),
        CONSTRAINT USER_USER_ID_PK PRIMARY KEY (USERID)
);
    
CREATE TABLE CLUBS (
    CLUBID          NUMBER(7),
    CLUBNAME        VARCHAR2(255),
    NICHE           VARCHAR2(255),
        CONSTRAINT CLUB_ID_PK PRIMARY KEY (CLUBID)
    );
    
CREATE TABLE STAFFS (
    STAFFID         NUMBER(7),
    USERID          NUMBER(7),
    FULLNAME       VARCHAR2(255),
    POSITION        VARCHAR2(255),
        CONSTRAINT STAFF_ID_PK PRIMARY KEY (STAFFID),
        CONSTRAINT STAFF_USER_ID_FK FOREIGN KEY (USERID) REFERENCES USERS
    );
    
CREATE TABLE MEMBERS (
    MEMBERID        NUMBER(7),
    USERID          NUMBER(7),
    CLUBID          NUMBER(7),
    FULLNAME        VARCHAR2(255),
    AGE             NUMBER(3),
    MATRICNO        NUMBER(10),
    COURSE          VARCHAR2(255),
    KULLIYAH        VARCHAR(255),
    STATUS          VARCHAR2(255),
    DESIGNATION     VARCHAR2(255),
    POSITION        VARCHAR2(255),
        CONSTRAINT MEMBER_ID_PK PRIMARY KEY (MEMBERID),
        CONSTRAINT MEMBER_USER_ID_FK FOREIGN KEY (USERID) REFERENCES USERS,
        CONSTRAINT CLUB_ID_MEMBER_FK FOREIGN KEY (CLUBID) REFERENCES CLUBS
    );
    
CREATE TABLE CLUB_STAFF_MANAGEMENT (
    CLUBID          NUMBER(7),
    STAFFID         NUMBER(7),
        CONSTRAINT CLUB_MANAGEMENT_CLUB_ID_FK FOREIGN KEY (CLUBID) REFERENCES CLUBS,
        CONSTRAINT CLUB_MANAGEMENT_STAFF_ID_FK FOREIGN KEY (STAFFID) REFERENCES STAFFS
    );

    
CREATE TABLE USER_APPLICATION (
    APPLICATIONID       NUMBER(7),
    FULLNAME            VARCHAR2(255),
    EMAIL               VARCHAR2(255),
    AGE                 NUMBER(3),
    MATRICNO            NUMBER(10),
    COURSE              VARCHAR2(255),
    KULLIYAH            VARCHAR(255),
    CLUBID              NUMBER(7),
    APPLICATION_STATUS  VARCHAR2(15) CHECK(APPLICATION_STATUS IN ('processing', 'accepted', 'rejected')),
        CONSTRAINT CLUB_ID_FK FOREIGN KEY (CLUBID) REFERENCES CLUBS,
        CONSTRAINT APPLICATION_ID_PK PRIMARY KEY (APPLICATIONID)
    );
    
CREATE SEQUENCE user_id_seq START WITH 1;

CREATE OR REPLACE TRIGGER user_on_create
    BEFORE INSERT ON USERS
    FOR EACH ROW
BEGIN
    SELECT user_id_seq.nextval
    INTO :new.userid
    FROM DUAL;
END;
/

CREATE SEQUENCE club_id_seq START WITH 1;

CREATE OR REPLACE TRIGGER club_on_create
    BEFORE INSERT ON CLUBS
    FOR EACH ROW
BEGIN
    SELECT club_id_seq.nextval
    INTO :new.clubid
    FROM DUAL;
END;
/

CREATE SEQUENCE staff_id_seq START WITH 1;

CREATE OR REPLACE TRIGGER staff_on_create
    BEFORE INSERT ON STAFFS
    FOR EACH ROW
BEGIN
    SELECT staff_id_seq.nextval
    INTO :new.staffid
    FROM DUAL;
END;
/

CREATE SEQUENCE member_id_seq START WITH 1;

CREATE OR REPLACE TRIGGER member_on_create
    BEFORE INSERT ON MEMBERS
    FOR EACH ROW
BEGIN
    SELECT member_id_seq.nextval
    INTO :new.memberid
    FROM DUAL;
END;
/

CREATE SEQUENCE application_id_seq START WITH 1;

CREATE OR REPLACE TRIGGER user_application_on_create
    BEFORE INSERT ON user_application
    FOR EACH ROW
BEGIN
    SELECT application_id_seq.nextval
    INTO :new.applicationid
    FROM DUAL;
END;
/
    